import json

import pandas as pd
import streamlit as st
from metadata_db import (
    delete_row,
    fetch_table,
    get_engine,
    insert_row,
    safe_str,
    to_json_text,
    update_row,
)

st.set_page_config(page_title="Source Systems", page_icon="🔌", layout="wide")
st.title("Source Systems")

SYSTEM_TYPES = ["database", "api", "file_drop", "saas"]

# connector_kind is nullable -- NULL means this feed's landing/raw/clean
# assets are hand-written (e.g. customers/sales), not generated by
# scripts/generate_dagster_pipeline.py's connector-driven codegen. The
# sentinel label maps to None on submit/index-lookup, matching the DDL
# check constraint's own 4 real values (metadata/db/init/01_platform_metadata.sql).
NO_CONNECTOR_LABEL = "(none -- hand-written asset file)"
CONNECTOR_KINDS = ["postgres", "csv", "json_file", "rest"]
CONNECTOR_KIND_OPTIONS = [NO_CONNECTOR_LABEL] + CONNECTOR_KINDS

engine = get_engine()
df = fetch_table(engine, "source_system", order_by="code")

st.dataframe(df, use_container_width=True, hide_index=True)
st.divider()

mode = st.radio("Action", ["Add new", "Edit existing", "Delete existing"], horizontal=True)

# No st.form() on this page -- see Learnings.md, "Cross-field reactivity is
# impossible inside st.form()". Every widget is plain and reruns live;
# nothing writes to the DB until its own st.button() is the one just
# clicked, so this loses no safety. "Add new" replaces st.form's free
# clear_on_submit with a session_state generation counter: bumping it after
# a successful insert changes every widget's key, so Streamlit treats the
# next render as brand-new widgets with fresh (blank) defaults instead of
# remembering the just-submitted values.
if mode == "Add new":
    if "add_source_system_gen" not in st.session_state:
        st.session_state["add_source_system_gen"] = 0
    key = f"add_ss_{st.session_state['add_source_system_gen']}"

    code = st.text_input("Code", key=f"{key}_code")
    name = st.text_input("Name", key=f"{key}_name")
    description = st.text_area("Description", key=f"{key}_description")
    system_type = st.selectbox("System type", SYSTEM_TYPES, key=f"{key}_system_type")
    connector_kind_label = st.selectbox(
        "Connector kind", CONNECTOR_KIND_OPTIONS,
        help="Which generic connector (processing/connectors/) generates this feed's landing/raw/clean "
        "assets. Leave as none for a hand-written asset file (e.g. customers/sales).",
        key=f"{key}_connector_kind",
    )
    base_location = st.text_input(
        "Base location",
        help="Root for connectivity: a SQL Server name, a storage account container, an API base URL",
        key=f"{key}_base_location",
    )
    connection_user = st.text_input("Connection user", key=f"{key}_connection_user")
    connection_secret = st.text_input(
        "Connection secret",
        help="Not the actual secret -- a reference/path to where it lives in a vault",
        key=f"{key}_connection_secret",
    )
    connection_config = st.text_area("Connection config (JSON)", value="{}", key=f"{key}_connection_config")
    is_active = st.checkbox("Active", value=True, key=f"{key}_is_active")
    submitted = st.button("Create", key=f"{key}_submit")

    if submitted:
        try:
            cfg = json.loads(connection_config or "{}")
        except json.JSONDecodeError as e:
            st.error(f"Connection config is not valid JSON: {e}")
        else:
            if not code or not name:
                st.error("Code and name are required.")
            else:
                try:
                    insert_row(
                        engine,
                        "source_system",
                        {
                            "code": code,
                            "name": name,
                            "description": description or None,
                            "system_type": system_type,
                            "connector_kind": None if connector_kind_label == NO_CONNECTOR_LABEL else connector_kind_label,
                            "base_location": base_location or None,
                            "connection_user": connection_user or None,
                            "connection_secret": connection_secret or None,
                            "connection_config": json.dumps(cfg),
                            "is_active": is_active,
                        },
                        json_columns={"connection_config"},
                    )
                    st.success(f"Created source system '{code}'")
                    st.session_state["add_source_system_gen"] += 1
                    st.rerun()
                except Exception as e:
                    st.error(f"Failed to create: {e}")

elif mode == "Edit existing":
    if df.empty:
        st.info("No source systems yet.")
    else:
        selected_code = st.selectbox("Select source system", df["code"])
        row = df[df["code"] == selected_code].iloc[0]
        key = f"edit_ss_{row['id']}"

        name = st.text_input("Name", value=safe_str(row["name"]), key=f"{key}_name")
        description = st.text_area("Description", value=safe_str(row["description"]), key=f"{key}_description")
        system_type = st.selectbox(
            "System type", SYSTEM_TYPES, index=SYSTEM_TYPES.index(row["system_type"]), key=f"{key}_system_type"
        )
        current_connector_kind = None if pd.isna(row["connector_kind"]) else row["connector_kind"]
        connector_kind_label = st.selectbox(
            "Connector kind", CONNECTOR_KIND_OPTIONS,
            index=CONNECTOR_KIND_OPTIONS.index(current_connector_kind or NO_CONNECTOR_LABEL),
            help="Which generic connector (processing/connectors/) generates this feed's landing/raw/clean "
            "assets. Leave as none for a hand-written asset file (e.g. customers/sales).",
            key=f"{key}_connector_kind",
        )
        base_location = st.text_input(
            "Base location", value=safe_str(row["base_location"]), key=f"{key}_base_location"
        )
        connection_user = st.text_input(
            "Connection user", value=safe_str(row["connection_user"]), key=f"{key}_connection_user"
        )
        connection_secret = st.text_input(
            "Connection secret", value=safe_str(row["connection_secret"]), key=f"{key}_connection_secret"
        )
        connection_config = st.text_area(
            "Connection config (JSON)", value=to_json_text(row["connection_config"]), key=f"{key}_connection_config"
        )
        is_active = st.checkbox("Active", value=bool(row["is_active"]), key=f"{key}_is_active")
        submitted = st.button("Save changes", key=f"{key}_submit")

        if submitted:
            try:
                cfg = json.loads(connection_config or "{}")
            except json.JSONDecodeError as e:
                st.error(f"Connection config is not valid JSON: {e}")
            else:
                try:
                    update_row(
                        engine,
                        "source_system",
                        "id",
                        row["id"],
                        {
                            "name": name,
                            "description": description or None,
                            "system_type": system_type,
                            "connector_kind": None if connector_kind_label == NO_CONNECTOR_LABEL else connector_kind_label,
                            "base_location": base_location or None,
                            "connection_user": connection_user or None,
                            "connection_secret": connection_secret or None,
                            "connection_config": json.dumps(cfg),
                            "is_active": is_active,
                        },
                        json_columns={"connection_config"},
                    )
                    st.success(f"Updated '{selected_code}'")
                    st.rerun()
                except Exception as e:
                    st.error(f"Failed to update: {e}")

else:  # Delete existing
    if df.empty:
        st.info("No source systems yet.")
    else:
        selected_code = st.selectbox("Select source system to delete", df["code"])
        row = df[df["code"] == selected_code].iloc[0]
        st.warning(
            f"This will permanently delete '{selected_code}'. "
            "Data feeds referencing it must be deleted first."
        )
        if st.button("Delete", type="primary"):
            try:
                delete_row(engine, "source_system", "id", row["id"])
                st.success(f"Deleted '{selected_code}'")
                st.rerun()
            except Exception as e:
                st.error(f"Failed to delete: {e}")
