name: "domain_iot_telemetry"
version: "1.0.0"
config-version: 2

profile: "domain_iot_telemetry"

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  domain_iot_telemetry:
    staging:
      +materialized: incremental
      +incremental_strategy: delete+insert
    model:
      +materialized: incremental
      +incremental_strategy: delete+insert
    serve:
      +materialized: view
