version: 2

models:
  - name: stg_customers
    tags: [customers]
    columns:
      - name: customer_id
        tests: [not_null]
      - name: email
        tests: [not_null]
      - name: _key_hash
        tests: [not_null, unique]

  - name: stg_sales
    tags: [sales]
    columns:
      - name: invoice_id
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: total
        tests: [not_null]
      - name: _key_hash
        tests: [not_null, unique]
      - name: payment_method
        tests:
          - not_null
          - accepted_values:
              values: ["Cash", "Credit card", "Ewallet"]
      - name: customer_type
        tests:
          - not_null
          - accepted_values:
              values: ["Member", "Normal"]
      - name: gender
        tests:
          - not_null
          - accepted_values:
              values: ["Male", "Female"]

  - name: stg_financial_transactions
    tags: [financial_transactions]
    columns:
      - name: transaction_id
        tests: [not_null]
      - name: posted_date
        tests: [not_null]
      - name: _key_hash
        tests: [not_null, unique]

  - name: stg_police_crimes
    tags: [police_crimes]
    columns:
      - name: id
        tests: [not_null]
      - name: category
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: _key_hash
        tests: [not_null, unique]
