"""Generates the dbt `clean` source declarations (models/staging/_sources.yml)
from every active data_feed row.

Previously a hand-maintained file at this same path -- any new feed's
models (hand-written staging, or an ODS passthrough, see
scripts/generate_ods_models.py) reading `source('clean', '<feed>')` would
silently fail `dbt parse` ("depends on a source ... which was not found")
until a human remembered to add an entry here by hand. Same "must exist on
disk before dbt parse builds target/manifest.json" category as every other
generate_*.py script in this project.

Deliberately NOT placed under models/staging/generated/ -- that directory
is generate_ods_models.py's own exclusive output, which it wipes and fully
recreates every run; sharing it would mean this file gets silently deleted
every time ODS regenerates (confirmed the hard way). A single generated
*file* living directly in its normal folder (with a "DO NOT EDIT" header),
same convention as pipeline_generated.py/clean_source_tables_generated.py,
avoids the collision entirely -- only a script that owns a whole
*directory* of many generated files needs its own generated/ subfolder.

Fully regenerates on every run (wipe-and-rewrite) -- 100% derived from
data_feed, nothing hand-written to protect, same reasoning as
generate_serve_views.py's schema.yml.
"""

import os
from pathlib import Path

import psycopg

CONN_KWARGS = dict(
    host=os.environ.get("POSTGRES_HOST", "localhost"),
    port=int(os.environ.get("POSTGRES_PORT", "5432")),
    user=os.environ.get("POSTGRES_USER", "platform"),
    password=os.environ.get("POSTGRES_PASSWORD", "platform"),
    dbname=os.environ.get("POSTGRES_DB", "platform_metadata"),
)

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "dbt" / "data_platform" / "models" / "staging" / "_sources.yml"


def fetch_active_feed_names(cur) -> list[str]:
    cur.execute("select friendly_name from data_feed where is_active = true order by friendly_name")
    return [row[0] for row in cur.fetchall()]


def render_sources_yml(feed_names: list[str]) -> str:
    lines = [
        "# GENERATED by scripts/generate_sources.py -- DO NOT EDIT BY HAND.",
        "# Regenerate via `just orchestration::generate-sources`.",
        "version: 2",
        "",
        "sources:",
        "  - name: clean",
        "    database: iceberg",
        "    schema: clean",
        "    tables:",
    ]
    for name in feed_names:
        lines.append(f"      - name: {name}")
    return "\n".join(lines) + "\n"


def generate(feed_names: list[str], output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_sources_yml(feed_names))
    return output_path


def main() -> None:
    with psycopg.connect(**CONN_KWARGS) as conn, conn.cursor() as cur:
        feed_names = fetch_active_feed_names(cur)

    path = generate(feed_names, OUTPUT_PATH)
    print(f"Generated clean source declarations for {len(feed_names)} active data_feed row(s) at {path.relative_to(REPO_ROOT)}.")


if __name__ == "__main__":
    main()
