"""Generates the model layer's deletion-synthesis intermediate models
(`int_<feed>_with_deletes.sql`) from `model_feed` + `schema_registry` — one
per `deletions_enabled=true` model_feed row, so nobody hand-authors this
model per feed (Roadmap.md "Deletion mechanism").

Deliberately a standalone build-time script, not a Dagster op — same
reasoning as generate_serve_views.py (dagster-dbt's `@dbt_assets` reads
target/manifest.json at Python-import time, before any run executes, so
these files have to exist on disk before `dbt parse` builds that manifest).

Column lists come from schema_registry.column_definitions (the current
version for the model_feed's staging_source_data_feed_id), not live Trino
introspection -- keeps this resolvable from Postgres alone at build time,
consistent with every other codegen step in this project, and avoids the
composite-key Jinja gymnastics a dynamic `adapter.get_columns_in_relation()`
approach would need.

Fully regenerates `models/model/dimensions/generated/` on every run (clears
first) so stale files never linger after a model_feed row's
deletions_enabled flips or a row is removed.
"""

import os
import shutil
from pathlib import Path

import psycopg

CONN_KWARGS = dict(
    host=os.environ.get("POSTGRES_HOST", "localhost"),
    port=int(os.environ.get("POSTGRES_PORT", "5432")),
    user=os.environ.get("POSTGRES_USER", "platform"),
    password=os.environ.get("POSTGRES_PASSWORD", "platform"),
    dbname=os.environ.get("POSTGRES_DB", "platform_metadata"),
)

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "dbt" / "data_platform" / "models" / "model" / "dimensions" / "generated"


def fetch_deletion_synthesis_feeds(cur) -> list[dict]:
    cur.execute(
        """
        select
            df.code as feed_code,
            df.id as data_feed_id,
            mf.business_key_columns
        from model_feed mf
        join data_feed df on df.id = mf.staging_source_data_feed_id
        where mf.is_active = true and mf.deletions_enabled = true
        order by df.code
        """
    )
    columns = [desc.name for desc in cur.description]
    return [dict(zip(columns, row)) for row in cur.fetchall()]


def fetch_current_columns(cur, data_feed_id: str) -> list[str]:
    cur.execute(
        "select column_definitions from schema_registry where data_feed_id = %s and is_current",
        (data_feed_id,),
    )
    row = cur.fetchone()
    if row is None:
        raise ValueError(f"No current schema_registry entry for data_feed_id={data_feed_id!r}")
    return [c["name"] for c in sorted(row[0], key=lambda c: c["ordinal"])]


def _render_model(*, feed_code: str, all_columns: list[str], business_key_columns: list[str]) -> str:
    cols_csv = ", ".join(all_columns)
    keys_csv = ", ".join(business_key_columns)
    return f"""{{{{ config(materialized='view', tags=['{feed_code}']) }}}}

{{#
    Deletion synthesis for a deletions_enabled model_feed (see Roadmap.md
    "Deletion mechanism"). Generated by
    scripts/generate_deletion_synthesis_views.py from model_feed +
    schema_registry -- not hand-authored, so a second deletions_enabled
    feed doesn't need its own copy-pasted model.

    Compares stg_{feed_code} (every business key ever seen, cumulative --
    staging never shrinks) against clean.{feed_code} (this run's true full
    snapshot -- clean is a fresh per-run load, not cumulative, see
    Roadmap.md "Layer Model"). A key in staging but missing from clean's
    current run is a deletion; its last-known attributes are carried
    forward from staging with is_deleted=true.

    Deliberately does NOT read the downstream Type-2 snapshot's own
    current state to check "is this key already marked deleted" -- that
    would be a circular ref() (this model feeds the snapshot, not the
    other way around). Not needed anyway: a repeatedly-synthesized
    is_deleted=true row for an already-deleted key has the same
    _attr_hash every run (tracked columns are frozen once deleted, and
    is_deleted stays true), so the snapshot's check_cols gate naturally
    produces zero new versions for it. Same idempotency mechanism already
    doing the work, not extra logic.
#}}

with all_known_keys as (

    select {cols_csv}
    from {{{{ ref('stg_{feed_code}') }}}}

),

current_source_keys as (

    select {keys_csv}
    from {{{{ source('clean', '{feed_code}') }}}}

),

active as (

    select {cols_csv}, false as is_deleted
    from all_known_keys
    where ({keys_csv}) in (select {keys_csv} from current_source_keys)

),

deleted as (

    select {cols_csv}, true as is_deleted
    from all_known_keys
    where ({keys_csv}) not in (select {keys_csv} from current_source_keys)

)

select * from active
union all
select * from deleted
"""


def generate(feeds: list[dict], columns_by_feed: dict[str, list[str]], output_dir: Path) -> list[Path]:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    written = []
    for row in feeds:
        feed_code = row["feed_code"]
        path = output_dir / f"int_{feed_code}_with_deletes.sql"
        path.write_text(
            _render_model(
                feed_code=feed_code,
                all_columns=columns_by_feed[feed_code],
                business_key_columns=row["business_key_columns"],
            )
        )
        written.append(path)

    return written


def main() -> None:
    with psycopg.connect(**CONN_KWARGS) as conn, conn.cursor() as cur:
        feeds = fetch_deletion_synthesis_feeds(cur)
        columns_by_feed = {row["feed_code"]: fetch_current_columns(cur, row["data_feed_id"]) for row in feeds}

    written = generate(feeds, columns_by_feed, OUTPUT_DIR)
    print(f"Generated {len(written)} deletion-synthesis model(s) for {len(feeds)} deletions_enabled model_feed row(s) in {OUTPUT_DIR}.")


if __name__ == "__main__":
    main()
