"""Generates the dbt `clean` source declarations
(dbt/domains/<domain>/models/staging/_sources.yml) from every active
data_feed row -- one file per domain now, not one shared file, since each
domain is its own dbt project (see Roadmap.md "multi-project dbt split").

Previously a hand-maintained single file; any new feed's models (hand-
written staging, or an ODS passthrough) reading `source('clean', '<feed>')`
would silently fail `dbt parse` ("depends on a source ... which was not
found") until a human remembered to add an entry here by hand.

A feed can legitimately appear in more than one domain's _sources.yml --
`clean.<feed>` is a plain physical source() any domain project can declare,
not something one project owns exclusively.

Fully regenerates every domain's _sources.yml on every run (wipe-and-
rewrite) -- 100% derived from data_feed/lakehouse_models, nothing
hand-written to protect.
"""

import os
from pathlib import Path

import psycopg

from generate_domain_projects import slugify_domain

CONN_KWARGS = dict(
    host=os.environ.get("POSTGRES_HOST", "localhost"),
    port=int(os.environ.get("POSTGRES_PORT", "5432")),
    user=os.environ.get("POSTGRES_USER", "platform"),
    password=os.environ.get("POSTGRES_PASSWORD", "platform"),
    dbname=os.environ.get("POSTGRES_DB", "platform_metadata"),
)

REPO_ROOT = Path(__file__).resolve().parents[1]
DOMAINS_DIR = REPO_ROOT / "dbt" / "domains"


def fetch_domain_feeds(cur) -> dict[str, set[str]]:
    """domain -> set of feed friendly_names that domain's _sources.yml
    needs to declare. Real domains: union of depends_on_feeds across that
    domain's lakehouse_models rows. ODS domains: feeds sharing that
    batch_ods_name."""
    domain_feeds: dict[str, set[str]] = {}

    cur.execute(
        """
        select lm.model_schema, df.friendly_name
        from lakehouse_models lm
        join data_feed df on df.id::text = any(string_to_array(lm.depends_on_feeds, ','))
        where lm.is_active = true and df.is_active = true
        """
    )
    for model_schema, feed_name in cur.fetchall():
        domain_feeds.setdefault(slugify_domain(model_schema), set()).add(feed_name)

    cur.execute(
        """
        select batch_ods_name, friendly_name
        from data_feed
        where ods_enabled = true and batch_ods_name is not null and is_active = true
        """
    )
    for batch_ods_name, feed_name in cur.fetchall():
        domain_feeds.setdefault(slugify_domain(batch_ods_name), set()).add(feed_name)

    return domain_feeds


def render_sources_yml(feed_names: list[str]) -> str:
    lines = [
        "# GENERATED by scripts/generate_sources.py -- DO NOT EDIT BY HAND.",
        "# Regenerate via `just orchestration::generate-sources`.",
        "version: 2",
        "",
        "sources:",
        "  - name: clean",
        "    database: iceberg",
        "    schema: clean",
        "    tables:",
    ]
    for name in feed_names:
        lines.append(f"      - name: {name}")
    return "\n".join(lines) + "\n"


def generate(domain_feeds: dict[str, set[str]], domains_dir: Path) -> list[Path]:
    written = []
    for domain, feed_names in domain_feeds.items():
        output_path = domains_dir / domain / "models" / "staging" / "_sources.yml"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(render_sources_yml(sorted(feed_names)))
        written.append(output_path)
    return written


def main() -> None:
    with psycopg.connect(**CONN_KWARGS) as conn, conn.cursor() as cur:
        domain_feeds = fetch_domain_feeds(cur)

    written = generate(domain_feeds, DOMAINS_DIR)
    print(f"Generated {len(written)} domain _sources.yml file(s) across {len(domain_feeds)} domain(s).")
    for p in written:
        print(f"  {p.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
