name: "domain_sales"
version: "1.0.0"
config-version: 2

profile: "domain_sales"

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  domain_sales:
    staging:
      +materialized: incremental
      +incremental_strategy: delete+insert
    model:
      +materialized: incremental
      +incremental_strategy: delete+insert
    serve:
      +materialized: view
