import os

from dagster import Definitions

from dagster_data_platform.assets.extraction_assets import clean_customers, extraction_customers, raw_customers
from dagster_data_platform.assets.financial_assets import archive_financial_transactions, financial_transactions_sensor
from dagster_data_platform.assets.sales_assets import clean_sales, extraction_sales, raw_sales
from dagster_data_platform.pipeline_generated import (
    ALL_CONNECTOR_ASSETS,
    ALL_DBT_ASSETS,
    ALL_EXTRACTION_JOBS,
    ALL_MODELING_JOBS,
    ALL_SCHEDULES,
    ALL_SERVING_JOBS,
    master_pipeline,
)
from dagster_data_platform.resources.iceberg_resource import IcebergCatalogResource
from dagster_data_platform.resources.postgres_metadata_resource import PostgresMetadataResource

# metadata_runs/financial_transactions/police_crimes' extraction/raw/clean
# assets used to be hand-written here (metadata_runs_assets.py,
# financial_assets.py, police_assets.py) -- now generated by
# scripts/generate_dagster_pipeline.py from source_system.connector_kind
# (see ALL_CONNECTOR_ASSETS in pipeline_generated.py). customers/sales stay
# hand-written -- their source_system.connector_kind is NULL (synthetic
# in-memory stub generators, not a real connector-backed source).
#
# No "dbt" resource entry here anymore, and no per-domain DbtProject/
# DbtCliResource wiring either (see Roadmap.md "multi-project dbt split") --
# each domain's dbt assets close over their own DbtCliResource instance
# directly inside dbt_assets.py's _build_transformation_assets_for_domain/
# _build_serving_assets_for_domain (constructed from a DbtProject discovered
# via pipeline_generated.py's own dbt/domains/*/ glob), rather than being
# Dagster-injected via a resources={} key. That's a deliberate deviation
# from registering N uniquely-keyed resources here: every domain's
# @dbt_assets function would otherwise need a uniquely-NAMED parameter (not
# just a unique resource instance) for Dagster's by-name resource matching
# to route each domain to its own project dir -- see
# _build_transformation_assets_for_domain's docstring for the full
# reasoning, confirmed against the installed dagster-dbt source.
defs = Definitions(
    assets=[
        extraction_customers,
        raw_customers,
        clean_customers,
        extraction_sales,
        raw_sales,
        clean_sales,
        archive_financial_transactions,
        *ALL_CONNECTOR_ASSETS,
        *ALL_DBT_ASSETS,
    ],
    jobs=ALL_EXTRACTION_JOBS + ALL_MODELING_JOBS + ALL_SERVING_JOBS + [master_pipeline],
    sensors=[financial_transactions_sensor],
    schedules=ALL_SCHEDULES,
    resources={
        "postgres_metadata": PostgresMetadataResource(
            host=os.environ.get("POSTGRES_HOST", "localhost"),
            port=int(os.environ.get("POSTGRES_PORT", "5432")),
            user=os.environ.get("POSTGRES_USER", "platform"),
            password=os.environ.get("POSTGRES_PASSWORD", "platform"),
            dbname=os.environ.get("POSTGRES_DB", "platform_metadata"),
        ),
        "iceberg_catalog": IcebergCatalogResource(
            polaris_host=os.environ.get("POLARIS_HOST", "localhost"),
            polaris_port=int(os.environ.get("POLARIS_PORT", "8181")),
            minio_host=os.environ.get("MINIO_HOST", "localhost"),
            minio_port=int(os.environ.get("MINIO_PORT", "9000")),
        ),
    },
)
