import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

from dagster import AssetExecutionContext, Output, asset

from dagster_data_platform.pipeline_generated import DOMAIN_FEEDS, TRANSFORMATION_ASSETS

FEED_FRIENDLY_NAME = "financial_transactions"
FEED_POOL = f"feed:{FEED_FRIENDLY_NAME}"
LANDING_SUBDIR = "landing/financial_transactions"
RAW_SUBDIR = "raw/financial_transactions"
ARCHIVE_SUBDIR = "archive/financial_transactions"

# TRANSFORMATION_ASSETS is keyed by DOMAIN now, not by feed (see Roadmap.md
# "multi-project dbt split") -- a domain can span several feeds' models, so
# this feed's own transformation dependency has to be resolved via
# DOMAIN_FEEDS (which domain(s) actually build this feed's staging model),
# not a hardcoded domain name. Today this resolves to exactly one domain
# ("sales", via fct_daily_financial_activity) but is computed generically
# so it keeps working if that ever changes -- a feed genuinely depended on
# by zero domains has nothing to wait for (deps=[]), matching the same
# "no hand-modeled/ODS consumer -> no transformation happens for this feed"
# reality as the police_crimes ODS decision elsewhere in this migration.
_OWNING_DOMAINS = [domain for domain, feeds in DOMAIN_FEEDS.items() if FEED_FRIENDLY_NAME in feeds]

# extraction_financial_transactions/raw_financial_transactions/
# clean_financial_transactions used to live here -- now generated by
# scripts/generate_dagster_pipeline.py (source_system.connector_kind='csv'),
# see pipeline_generated.py. archive_financial_transactions stays
# hand-written: archiving isn't part of the standard extraction/validation
# contract every connector-driven feed shares, it's genuinely specific to
# this feed. The file-drop sensor that used to live here too
# (financial_transactions_sensor) has been retired -- it's now a generated
# sensor (ALL_SENSORS in pipeline_generated.py), driven by this feed's own
# sensor-type ingestion_triggers row rather than hardcoded here. See
# Roadmap.md/Backlog.md, Item 2+3's ingestion_triggers generalization.

# .../orchestration/dagster_data_platform/dagster_data_platform/assets/financial_assets.py
# -> repo root is 4 parents up, same convention as dbt_assets.py's
# REPO_ROOT. Only used as the *local* fallback -- inside the launched pod,
# DATA_LAKE_PATH=/data-lake is set explicitly (dagster.yaml's run_launcher
# env_vars), since /app/data-lake doesn't exist there -- the mount lands at
# the container root, not under the app's own code directory.
REPO_ROOT = Path(__file__).resolve().parents[4]


def _data_lake_dir() -> Path:
    return Path(os.environ["DATA_LAKE_PATH"]) if "DATA_LAKE_PATH" in os.environ else REPO_ROOT / "data-lake"


def _landing_dir() -> Path:
    return _data_lake_dir() / LANDING_SUBDIR


def _raw_dir() -> Path:
    return _data_lake_dir() / RAW_SUBDIR


def _archive_dir() -> Path:
    return _data_lake_dir() / ARCHIVE_SUBDIR


@asset(pool=FEED_POOL, group_name=FEED_FRIENDLY_NAME, deps=[TRANSFORMATION_ASSETS[d] for d in _OWNING_DOMAINS])
def archive_financial_transactions(context: AssetExecutionContext) -> Output[None]:
    """Archives this run's raw snapshot and wipes the landing files it
    came from -- only reachable once every domain that builds this feed's
    models (_OWNING_DOMAINS above) has fully succeeded (a plain `deps=`
    dependency; Dagster skips a downstream asset entirely if any of its
    dependencies failed, so a clean/dbt failure anywhere upstream leaves
    landing completely untouched for a retry -- no separate error handling
    needed here for that case). Deliberately depends on transformation, not
    serving -- the batch is considered "fully processed" once the model
    layer is built; serve views are just a read-side convenience on top.

    archive holds the long-term, disaster-recovery copy: one
    watermark-style timestamped folder (YYYY/MM/DD/HH/MM/SS) per run,
    holding everything that run ingested -- reload archived folders in
    run order to rebuild raw/clean/staging from scratch if ever needed.
    landing is wiped only now, at the very end, deliberately last: if
    anything upstream failed, this asset never runs at all, so landing
    still has the original files and a re-run has something to reprocess
    without needing to restore from archive.
    """
    raw_run_dir = _raw_dir() / f"run_id={context.run_id}"
    if not raw_run_dir.exists() or not any(raw_run_dir.iterdir()):
        # Nothing was new this run (raw_financial_transactions only writes
        # this folder when there were rows to process) -- nothing to
        # archive or wipe. Still a success, just a no-op.
        return Output(None, metadata={"archived_files": 0})

    now = datetime.now(timezone.utc)
    archive_run_dir = _archive_dir() / now.strftime("%Y/%m/%d/%H/%M/%S")
    archive_run_dir.mkdir(parents=True, exist_ok=True)

    landing_dir = _landing_dir()
    archived = 0
    for f in sorted(raw_run_dir.iterdir()):
        shutil.copy2(f, archive_run_dir / f.name)
        archived += 1
        landing_file = landing_dir / f.name
        if landing_file.exists():
            landing_file.unlink()

    return Output(None, metadata={"archived_files": archived, "archive_path": str(archive_run_dir)})
